repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=5000'] # 5 MB

  # Keep notebooks clean of outputs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  # Ruff for both Python and Notebooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
      # Linter: Fixes imports, unused vars, etc.
      - id: ruff
        args: [ --fix ]
      # Formatter: Standardizes code style
      - id: ruff-format
